version: "3"
services:
  frontend:
    container_name: gamafication-node-frontend
    build: .
    ports:
      - 5173:5173
    restart: always
    environment:
      VITE_BACKEND_URI: https://gamification-node-backend-dev.thewitslab.com

