version: "3"
services:
  frontend:
    container_name: ${SERVICE_NAME:-gamafication-frontend}
    build: .
    ports:
      - ${HOST_PORT:-5173}:5173
    restart: always
    networks:
      - gamafication-network-dev

networks:
  gamafication-network-dev:
    driver: bridge